version: "3.9"

services:
  db:
    container_name: db
    image: postgres:alpine
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    networks:
      - web-internal

  app:
    container_name: app
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    env_file: ./.env
    environment:
      - DB_HOST=db
      - DB_USER=$POSTGRES_USER
      - DB_PASS=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DB
      - DB_PORT=$POSTGRES_DOCKER_PORT
      - NODEM_USER=javier.beltmart@gmail.com
      - NODEM_PASSWORD=jyldoinnuzqxqprg
      - REACT_APP_SERVER_URL=$CLIENT_API_BASE_URL
    networks:
      - web-internal
      - web-external
    volumes:
      - public:/usr/src/app/public:rw

networks:
  web-internal:
  web-external:

volumes:
  pgdata:
  public:
