version: "3.9"

services:
  db:
    container_name: db
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    networks:
      - web-internal

  app:
    container_name: app
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    env_file: ./.env
    environment:
      - DB_HOST=db
      - DB_USER=$POSTGRES_USER
      - DB_PASS=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DB
      - DB_PORT=$POSTGRES_DOCKER_PORT

      - BASE_PATH=$BASE_PATH
      - REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL

      - NODEM_USER=$NODEM_USER
      - NODEM_PASSWORD=$NODEM_PASSWORD
    networks:
      - web-internal
      - web-external
    volumes:
      - public:/app/public:rw

networks:
  web-internal:
  web-external:

volumes:
  pgdata:
  public:
