const SOLICITUDES_TIPOS = {
  CONSULTA: "consulta",
  REVISION: "revisión",
};

const SOLICITUDES_ESTADOS = {
  PENDIENTE: "PENDIENTE",
  ACEPTADO: "ACEPTADO",
  RECHAZADO: "RECHAZADO",
  ATENDIDO: "ATENDIDO",
  AUSENTE: "AUSENTE",
};

const SOLICITUDES_COLORES = {
  ROJO: "#7E1717",
  VERDE: "#17594a",
};

var SOLICITUDES_TIPOS_ARRAY = Object.values(SOLICITUDES_TIPOS);
var SOLICITUDES_ESTADOS_ARRAY = Object.values(SOLICITUDES_ESTADOS);

export {
  SOLICITUDES_TIPOS,
  SOLICITUDES_TIPOS_ARRAY,
  SOLICITUDES_ESTADOS,
  SOLICITUDES_ESTADOS_ARRAY,
  SOLICITUDES_COLORES,
};
