const SOLICITUDES_TIPOS = {
  CONSULTA: "consulta",
  REVISION: "revisión",
};

var SOLICITUDES_TIPOS_ARRAY = Object.values(SOLICITUDES_TIPOS);

export { SOLICITUDES_TIPOS, SOLICITUDES_TIPOS_ARRAY };
