const SOLICITUDES_TIPOS = {
  CONSULTA: "consulta",
  REVISION: "revisión",
};

const SOLICITUDES_ESTADOS = {
  PENDIENTE: "pendiente",
  ACEPTADA: "aceptada",
  RECHAZADA: "rechazada",
};

var SOLICITUDES_TIPOS_ARRAY = Object.values(SOLICITUDES_TIPOS);
var SOLICITUDES_ESTADOS_ARRAY = Object.values(SOLICITUDES_ESTADOS);

export {
  SOLICITUDES_TIPOS,
  SOLICITUDES_TIPOS_ARRAY,
  SOLICITUDES_ESTADOS,
  SOLICITUDES_ESTADOS_ARRAY,
};
